# Technical stuff
canonifyURLS: true
enableRobotsTXT: true
frontmatter:
  date:
  - lastmod
  - date
languageCode: en-US
removePathAccents: true
summaryLength: 64
disableKinds: [taxonomy, term, section]

# Images
imaging:
  quality: 90
  exif:
    disableDate: true
    disableLatLong: true

# Meta
title: Infinitely Random
author:
  name: noClaps
baseURL: https://blog.zerolimits.dev

# Markup
markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true

# Privacy
privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

# Dev
disableLiveReload: true

# Minify
minify:
  minifyOutput: true