site_name: The Blog of Random
site_url: https://noclaps.github.io/blog/
site_description: A blog about the most random things you can think of, brought to you by the most interesting boring person you've ever met
repo_url: https://github.com/noClaps/blog
repo_name: ""
edit_uri: edit/main/docs/

plugins:
  - search:
      separator: '[\s\-\.]'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      js_files:
          - assets/javascripts/mathjax.js
          - assets/javascripts/accordion.js
      css_files:
          - assets/stylesheets/extra.css
  
markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: "#"
  - meta
  - pymdownx.caret

nav:
  - Science:
    - chaos-theory.md
    - collatz-conjecture.md
  - History:
    - history-of-toilet-paper.md
    - the-phalanx-formation.md
  - Tech:
    - Privacy, Security and Anonymity:
      - psa/intro.md
      - psa/messengers.md
    - posts/google.md
    
theme:
  font: false
  favicon: assets/images/favicon.svg
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - navigation.top
    - navigation.expand
  icon:
    logo: tcgmoo/favicon
    repo: material/github
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: tcgmoo/matrix
      link: https://matrix.to/#/@whatanerd:envs.net
      name: Matrix
      
extra_javascript:
  - assets/javascripts/mathjax.js
  - assets/javascripts/accordion.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
extra_css:
  - assets/stylesheets/extra.css
