name: Error
description: I'm reporting misinformation or improving your content, please update ASAP!
title: "[ERROR] "
labels: [error]
assignees:
  - noClaps
body:
- type: checkboxes
  attributes:
    label: Have you read the code of conduct?
    description: Please read the code of conduct before submitting an issue.
    options:
    - label: I have read the code of conduct
      required: true

- type: checkboxes
  attributes:
    label: Has this error already been reported?
    description: Check both open and closed issues to see if this error has already been reported.
    options:
    - label: My idea has not been reported yet
      required: true

- type: textarea
  attributes:
    label: Where have I made an error?
    description: You can provide a link directly to the error, or simply name the post, section, and line that's incorrect.
    placeholder: Be as accurate as you can, since this helps me find and correct the error quicker.
  validations:
    required: true

- type: textarea
  attributes:
    label: Correction
    description: What is the correction you would make?
    placeholder: |
      Provide links to sources to back up your correction, or I will close the issue until they are. 
      If you're suggesting improvements to the content, such as clearer wording or adding sources, then you can also write that here.

      You can use a format such as:
      **Correction**: <your correction here>, eg. Lorem ipsum
      **Sources**:
      - <link to source 1>, eg. https://example.com
      - <link to source 2>, eg. https://example.org
      - <link to source 3>, eg. https://vitepress.vuejs.org
      - ...

      A minimum of one source is required, but 2 or more are encouraged. Also, clean your links before sharing them here, please. I don't wanna be tracked. 
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: If there's anything else you wanna say that doesn't fit the above categories, you can share them here.
  validations:
    required: false