name: New post idea
description: I have a fun and exciting new idea for a post I want you to write about!
title: "[IDEA] "
labels: [idea]
assignees:
  - noClaps
body:
- type: checkboxes
  attributes:
    label: Have you read the code of conduct?
    description: Please read the code of conduct before submitting an issue.
    options:
    - label: I have read the code of conduct.
      required: true

- type: checkboxes
  attributes:
    label: Has this idea already been presented?
    description: Check both open and closed issues to see if your idea has already been presented.
    options:
    - label: My idea has not been presented yet.
      required: true

- type: textarea
  attributes:
    label: Description of your idea
    description: Tell me some details about your idea.
    placeholder: This helps me research it better and write a more accurate post about it. Go as in-depth as you would like to, the more details the better!
  validations:
    required: false

- type: textarea
  attributes:
    label: Links
    description: You can provide links related to your topic here.
    placeholder: This can help me understand the topic better, so it's not required but highly encouraged! (Preferably in English, but all languages are welcome!)
  validations:
    required: false

- type: textarea
  attributes:
    label: Anything else?
    description: If there's anything else you wanna say that doesn't fit the above categories, you can share them here.
  validations:
    required: false
